# Generated by Django 5.0.6 on 2024-07-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterBIKE', '0003_alter_usuario_apellido_alter_usuario_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
